In [1]:
import time

In [2]:
a = list(range(1000000))
b = list(range(1000000))

start_p = time.perf_counter()
c = [x + y for x, y in zip(a, b)]
end_p = time.perf_counter()
total_p = end_p - start_p
print("Python:", total_p)

Python: 0.06456960000014078


In [3]:
import numpy as np

In [4]:
a_np = np.array(a)
b_np = np.array(b)

start_n = time.perf_counter()
c_np = a_np + b_np
end_n = time.perf_counter()
total_n = end_n - start_n
print("NumPy:", total_n)

NumPy: 0.0023124999997889972


In [5]:
print(f"Numpy is faster than python by : {total_p/total_n:.2f}")

Numpy is faster than python by : 27.92


# Numpy

Python lists are : 
 - Flexible but slowfor numerical operations
 - Not designed for matrix math or
 - Does not support vectorised operation
 - Are memory inefficient for large numerical data

Why use numpy?
- Fast than pure python for numerical computation
- Vectorized operation (no explicit loops)
- Broadcasting (operate on arrays of different shape)
- Memory efficient
- Comes with powerful linear algebra, random tools etc

Use of numpy :
- Scientific python

In [6]:
# !pip install numpy

In [7]:
import numpy as np

# creating arrays in numpy

### 1. np.array()

In [8]:
arr_1 = np.array([1,2,3])

print(arr_1)
print(type(arr_1))

[1 2 3]
<class 'numpy.ndarray'>


In [9]:
arr_1

array([1, 2, 3])

In [10]:
type(arr_1[0])

numpy.int64

In [11]:
arr_2 = np.array([[1,2,3], [4,5,6]])

print(arr_2)

[[1 2 3]
 [4 5 6]]


In [12]:
arr_2[0]

array([1, 2, 3])

In [13]:
arr_2[0][2]

np.int64(3)

In [14]:
arr_2[1][2]

np.int64(6)

In [15]:
arr_3 = np.array([1,2,3, "hello"])

print(arr_3)
print(type(arr_3))

['1' '2' '3' 'hello']
<class 'numpy.ndarray'>


In [16]:
print(type(arr_3[1]))

<class 'numpy.str_'>


In [17]:
arr_4 = np.array([1,2,3], dtype=np.int8)
print(type(arr_4))

<class 'numpy.ndarray'>


In [18]:
type(arr_4[0])

numpy.int8

In [19]:
arr_5 = np.array([1,2,3, "hello"], dtype=np.float16)

ValueError: could not convert string to float: 'hello'

In [ ]:
arr_6 = np.array([1,2,3, "10"], dtype=np.float16)

In [ ]:
arr_6

array([ 1.,  2.,  3., 10.], dtype=float16)

In [ ]:
# arrays can have elements with only one data type

### 2. np.arange(start, stop, step)

In [ ]:
list(range(1, 11, 2))

[1, 3, 5, 7, 9]

In [ ]:
b = np.arange(1, 11, 2)

In [ ]:
b

array([1, 3, 5, 7, 9])

### 3. np.linspace(start, stop, num=x)
stop - inclusive

In [ ]:
np_linspace_1 = np.linspace(1,100,4)
print(np_linspace_1)
print(type(np_linspace_1))

[  1.  34.  67. 100.]
<class 'numpy.ndarray'>


In [ ]:
np_linspace_2 = np.linspace(1,10,10)
print(np_linspace_2)
print(type(np_linspace_2))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>


In [ ]:
for num in np.linspace(1,10,10):
    # print(type(num))
    print(num)
    # print(type(int(num)))
    # print("=================")

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [ ]:
for num in np.linspace(1,10,10, dtype=np.int8):
    print(num)

1
2
3
4
5
6
7
8
9
10


### 4. np.zeros(shape)

shape -> shape of matrix

In [ ]:
npz_1 = np.zeros(5)

In [ ]:
npz_1

array([0., 0., 0., 0., 0.])

In [ ]:
npz_2 = np.zeros((5,5), dtype=np.int8)
print(npz_2)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
npz_2 = np.zeros((5,5))
print(npz_2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
npz_3 = np.zeros((5,5,5))
print(npz_3)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [ ]:
npz_3.ndim

3

### 5. np.ones(shape)

shape -> shape of matrix

In [ ]:
npo_1 = np.ones((2,3))
print(npo_1)

[[1. 1. 1.]
 [1. 1. 1.]]


### 6. np.full(shape, fill_value)

shape -> shape of matrix

In [ ]:
npf_1 = np.full((2,3), 10)
print(npf_1)

[[10 10 10]
 [10 10 10]]


### 7. np.eye(shape)

shape -> shape of matrix

- does not exist in 1D
- min of 2D,shape

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [ ]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
np.eye(7,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

### 8. np.empty(shape)

In [ ]:
np.empty((2,2), dtype=np.int8)

array([[0, 0],
       [0, 1]], dtype=int8)

In [ ]:
np.empty((2,2), dtype=np.float16)

array([[0.   , 0.   ],
       [0.   , 1.984]], dtype=float16)

In [ ]:
start_e = time.perf_counter()
np.empty((5,5))
end_e = time.perf_counter()
total_e = end_e - start_e
print(total_e)

4.240000089339446e-05


In [ ]:
start_we = time.perf_counter()
np.ones((5,5))
end_we = time.perf_counter()
total_we = end_we - start_we
print(total_we)

5.390000114857685e-05


### 9. np.random.rand(shape)

random values between 0 and 1

- ML weights random initialization

In [ ]:
np.random.rand(2,8)

array([[0.65339572, 0.3644414 , 0.88792983, 0.65404473, 0.60644969,
        0.1896986 , 0.31136365, 0.32720686],
       [0.39949559, 0.4455743 , 0.39204205, 0.6491078 , 0.91083752,
        0.48799975, 0.73930809, 0.93253408]])

In [ ]:
# 1 D --> vector

# Numpy Array attributes

### 1. ndarray.shape

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


### 2. ndarray.ndim

In [ ]:
print(arr.ndim)

2


### 3. ndarray.size

Returns the total number of elements in the array.

In [ ]:
print(arr.size)

6


### 4. ndarray.dtype

Tells the data type of the array elements.

In [ ]:
print(arr.dtype)

int64


### 5. ndarray.itemsize

Returns the size in bytes of one element.

1 byte --> 8 bit

int8 --> 8 bit

int64 --> int8 * 8 --> int64

In [ ]:
print(arr.itemsize)

8


### 6. ndarray.nbytes
Total number of bytes consumed by the array.

In [ ]:
print(arr.nbytes)

48


### 7. ndarray.T

Returns the transpose of the array.

In [ ]:
print(arr) # 2 rows, 3 column

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


# Array Reshaping and resizing in numpy

###  1. reshape()

Change Shape Without Changing Data

##### Notes:
The total number of elements must remain the same.

reshape() returns a new view if possible (no copy).

You can use -1 to let NumPy infer one dimension:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)

(6,)


In [ ]:
# 2x3
# 3X2
# 4x2 -> No
# 6x1 -> Yes

In [ ]:
reshaped_1 = arr.reshape(2, 3)
print(reshaped_1)

[[1 2 3]
 [4 5 6]]


In [ ]:
reshaped_2 = arr.reshape(3, 2)
print(reshaped_2)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
reshaped_2 = arr.reshape(1, 6)
print(reshaped_2)
print(reshaped_2.ndim)

[[1 2 3 4 5 6]]
2


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 56, 100, 789])
print(arr.shape)

(9,)


In [ ]:
reshaped_3 = arr.reshape(3, -1)
print(reshaped_3.shape)


(3, 3)


In [ ]:
reshaped_3 = arr.reshape(-1, 3)
print(reshaped_3.shape)


(3, 3)


In [ ]:
reshaped_3 = arr.reshape(2, -1)
print(reshaped_3.shape)


ValueError: cannot reshape array of size 9 into shape (2,newaxis)