In [1]:
import time
import numpy as np

In [2]:
a = range(100000000)
b = range(100000000)
start = time.perf_counter()
total_val = [x+y for x, y in zip(a, b)]
end = time.perf_counter()
total_p = end - start
print(total_p)

7.659002999999757


In [3]:
a = np.array(a)
b = np.array(b)
start = time.perf_counter()
total_val = a + b
end = time.perf_counter()
total_n = end - start
print(total_n)
print(f"Numpy is faster than python {total_p/total_n:.2f} percentage")

1.1647398000000067
Numpy is faster than python 6.58 percentage


In [4]:
np.array([1,2,3,4, '76'], dtype=np.float64)


array([ 1.,  2.,  3.,  4., 76.])

In [5]:
arr = np.array([1,2,3,4, '76'])
type(arr[2])

numpy.str_

In [6]:
np.linspace(1,10, 10, dtype=np.int64)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
arr = np.zeros((2,3,2,5), dtype=np.int8)
print(arr, end='\n\n\n')
print('Dimentions: ', arr.ndim)
print('', end='\n\n')
print('Shape: ', arr.shape)

[[[[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]]]


Dimentions:  4


Shape:  (2, 3, 2, 5)


In [10]:
arr = np.ones((2,3,2,5), dtype=np.int8)
print(arr, end='\n\n\n')
print('Dimentions: ', arr.ndim)
print('', end='\n\n')
print('Shape: ', arr.shape)

[[[[1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]]]


 [[[1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]]]]


Dimentions:  4


Shape:  (2, 3, 2, 5)


In [11]:
arr = np.full((2,3,2,5), 13, dtype=np.int8)
print(arr, end='\n\n\n')
print('Dimentions: ', arr.ndim)
print('', end='\n\n')
print('Shape: ', arr.shape)

[[[[13 13 13 13 13]
   [13 13 13 13 13]]

  [[13 13 13 13 13]
   [13 13 13 13 13]]

  [[13 13 13 13 13]
   [13 13 13 13 13]]]


 [[[13 13 13 13 13]
   [13 13 13 13 13]]

  [[13 13 13 13 13]
   [13 13 13 13 13]]

  [[13 13 13 13 13]
   [13 13 13 13 13]]]]


Dimentions:  4


Shape:  (2, 3, 2, 5)


### Identity matrix

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.eye(5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.eye(5)[::-1]

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [15]:
np.eye(5,2, dtype=np.int16)

array([[1, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int16)

In [16]:
np.empty((5,5), dtype=np.int8)

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0]], dtype=int8)

In [17]:
np.empty((5), dtype=np.int8)

array([0, 0, 0, 0, 0], dtype=int8)

In [18]:
np.random.rand(3,3,3)

array([[[0.53669289, 0.83489464, 0.11258095],
        [0.98911886, 0.13295723, 0.43404078],
        [0.13400575, 0.97732461, 0.79083032]],

       [[0.81358444, 0.94538217, 0.96229801],
        [0.7032274 , 0.1641758 , 0.05979868],
        [0.86523878, 0.58999839, 0.6928061 ]],

       [[0.48606903, 0.72257975, 0.59351477],
        [0.4191731 , 0.62194919, 0.37144129],
        [0.09020336, 0.97807517, 0.3536149 ]]])

In [19]:
arr = np.random.rand(3,3,3)
print(arr.size)
print(arr.itemsize)
print(arr.nbytes)
print(arr.T)

27
8
216
[[[0.38088583 0.69559015 0.0714088 ]
  [0.2238118  0.03931204 0.63628643]
  [0.53354335 0.18506566 0.48336195]]

 [[0.19945331 0.68398932 0.48537411]
  [0.83668584 0.7214921  0.86273581]
  [0.88868707 0.48844584 0.93246681]]

 [[0.70702676 0.32019753 0.48278735]
  [0.53742124 0.83277943 0.28839115]
  [0.07022374 0.33274034 0.31163581]]]


In [20]:
np.random.randint(1, 100, 20, dtype=np.int8)

array([93, 36, 62, 54, 82, 69, 75, 16, 50,  4, 61, 40, 91, 17, 83, 60, 77,
       25, 25, 63], dtype=int8)

In [21]:
arr = np.random.randint(1, 100, 20, dtype=np.int8)
reshape = arr.reshape((4,-1))
print(reshape)
arr

[[92 11 26 96 47]
 [ 3 50 17 51 46]
 [32 79 31 41 83]
 [99 16 41 91 89]]


array([92, 11, 26, 96, 47,  3, 50, 17, 51, 46, 32, 79, 31, 41, 83, 99, 16,
       41, 91, 89], dtype=int8)

In [22]:
arr = np.random.randint(1, 100, 20, dtype=np.int8)
arr.resize((4,5))
arr

array([[24, 32, 38, 96, 78],
       [52, 55, 31, 31, 45],
       [11, 88, 70, 36, 11],
       [24, 95, 60, 19, 66]], dtype=int8)

In [23]:
arr.ravel()

array([24, 32, 38, 96, 78, 52, 55, 31, 31, 45, 11, 88, 70, 36, 11, 24, 95,
       60, 19, 66], dtype=int8)

In [24]:
arr[arr>60]

array([96, 78, 88, 70, 95, 66], dtype=int8)

In [25]:
arr[arr>60].size

6

In [26]:
arr.T

array([[24, 52, 11, 24],
       [32, 55, 88, 95],
       [38, 31, 70, 60],
       [96, 31, 36, 19],
       [78, 45, 11, 66]], dtype=int8)