In [1]:
import numpy as np

In [2]:
a_list = [1,2,3]
b_list = [4,5,6]

print(a_list + b_list)

[1, 2, 3, 4, 5, 6]


In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]


In [5]:
a*b # Element wise multiplication

array([ 4, 10, 18])

In [ ]:
print(np.dot(a,b)) # multiplication + summation

32


In [9]:
a_1 = np.array([[1,2,3],[4,5,6]])
b_1 = np.array([[1,2,3],[4,5,6]])

In [10]:
print(a_1.shape)
print(b_1.shape)

(2, 3)
(2, 3)


In [12]:
np.dot(a_1, b_1.T)

array([[14, 32],
       [32, 77]])

In [54]:
a_1@b_1.T

array([[14, 32],
       [32, 77]])

In [ ]:
# apple, banana, smartphone, toy, furniture
shop_sold_amazon = np.array([
    [100, 200, 20, 30, 5], # state-1-product-sold
    [200, 400, 40, 60, 10] # state-2-product-sold
])
print(shop_sold_amazon.shape)

(2, 5)


In [25]:
price_amazon = np.array([
    [30, 10, 1000, 10, 200], # state-1-price
    [34, 12, 1100, 11, 220] # state-2-price
])
print(price_amazon.shape)

(2, 5)


In [23]:
price_amazon.T

array([[  30,   34],
       [  10,   12],
       [1000, 1100],
       [  10,   11],
       [ 200,  220]])

In [26]:
sales = np.dot(shop_sold_amazon, price_amazon.T)

In [28]:
sales

# [[state_1(price_of_state_1), state_1(price_of_state_2)]
# [state_2(price_of_state_1), state_2(price_of_state_2)]]

array([[26300, 29230],
       [52600, 58460]])

In [33]:
diag = np.eye(2)
print(diag)

[[1. 0.]
 [0. 1.]]


In [34]:
np.sum(sales*diag)

np.float64(84760.0)

# Aggregation function

In [35]:
a_2 = np.array([1,2,3,4,5])

In [36]:
np.sum(a_2)

np.int64(15)

In [37]:
np.min(a_2)

np.int64(1)

In [ ]:
np.max(a_2)

np.int64(5)

In [ ]:
# [1,2,3,4,5]
a_3 = [1,2,100, 45, 450, 2, 5]
np.argmax(a_3) # index of the max element # not aggresation function

np.int64(4)

In [57]:
np.argmin(a_3)

np.int64(0)

In [51]:
price_amazon = np.array([
    [30, 10, 1000, 10, 200], # state-1-price
    [34, 12, 1100, 11, 220], # state-2-price,
    [34, 12, 1100, 11, 220]
])

In [43]:
np.sum(price_amazon)

np.int64(2627)

In [ ]:
np.sum(price_amazon, axis=0)
# axis->0 means sum over rows, keep columns

array([  64,   22, 2100,   21,  420])

In [ ]:
np.sum(price_amazon, axis=1)
# axis->1 means sum over columns, keep rows

array([1250, 1377])

In [46]:
np.mean(a_3)

np.float64(86.42857142857143)

In [47]:
np.mean(price_amazon)

np.float64(262.7)

In [ ]:
np.mean(price_amazon, axis=1)

array([250. , 275.4])

In [ ]:
np.std(price_amazon, axis=1)

array([381.73289091, 419.66539052, 419.66539052])

In [58]:
np.var(price_amazon, axis=1)

array([145720.  , 176119.04, 176119.04])

In [53]:
np.cumsum([1,2,4,5,6,100])

array([  1,   3,   7,  12,  18, 118])

In [56]:
np.median(price_amazon, axis=1)

array([30., 34., 34.])

In [60]:
data = np.array([1, 3, 5, 7, 9])
print(np.percentile(data, 50))

5.0


# sort, search, counting functions

In [ ]:
arr = np.array([3, 6, 1, 1, 1, 1, 8, 2, 5, 6])

In [64]:
len(arr)

10

In [ ]:
print("Sorted:", np.sort(arr))
print("Sorted indices:", np.argsort(arr))
# Instead of returning the sorted values themselves, 
# it returns an array of indices that, when used to index the original array, would produce a sorted sequence.

Sorted: [1 1 1 1 2 3 5 6 6 8]
Sorted indices: [3 2 5 4 7 0 8 1 9 6]


In [ ]:
print("Insert 4 position:", np.searchsorted(np.sort(arr), 4))
print("Unique elements:", np.unique(arr))
print("Count of each element:", np.bincount(arr)) # MIN - 0 , maX - 8

# 0,1,2,3,4,5,6,7,8
# 0,4,1....

Insert 4 position: 6
Unique elements: [1 2 3 5 6 8]
Count of each element: [0 4 1 1 0 1 2 0 1]


In [68]:
arr_new = np.array([3, 6, 1, 1, 1, 1, 1.2, 8, 2, 5, 6])

In [70]:
arr_new

array([3. , 6. , 1. , 1. , 1. , 1. , 1.2, 8. , 2. , 5. , 6. ])

In [ ]:
print("Count of each element:", np.bincount(arr_new), rul)

TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'

In [74]:
arr = np.array([1, 2, 3, 4])
for x in arr:
    print(x)

1
2
3
4


In [75]:
arr_2d = np.array([[1, 2], [3, 4]])

for x in arr_2d:
    print(x)

[1 2]
[3 4]


In [77]:
list(range(0,11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
np.arange(8)
# 2,4
# 1,8
# 2,2,2
# 2,6 (BEST)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [81]:
arr = np.arange(8).reshape(2,2,2)
arr

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
arr.ndim # attibute of the class

3

In [83]:
for i in arr:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [84]:
for x in np.nditer(arr):
    print(x)

0
1
2
3
4
5
6
7


In [86]:
a = np.array([1, 2, 3])

In [87]:
b = a # 

In [88]:
print(id(a))
print(id(b))

2116798518768
2116798518768


In [89]:
b[0] = 100

In [90]:
print(a)

[100   2   3]


In [91]:
b = a.copy()

In [92]:
print(id(a))
print(id(b))

2116798518768
2117406015184


In [ ]:
a = np.array([1, 2, 3,])

b = a.view()



In [95]:
print(id(a))
print(id(b))

2117413010000
2117413010480


In [96]:
print(np.shares_memory(a, b))

True


In [97]:
# vstack

a = np.array([[1,2]])
b = np.array([[3,4]])

In [98]:
print(np.vstack((a,b)))

[[1 2]
 [3 4]]


In [99]:
print(np.hstack((a,b)))

[[1 2 3 4]]


# numpy char and strings

In [100]:
# np.char.<function_name>()

In [102]:
# 1. np.add()

# "hello" + "hello"

a = np.array(['hello', 'world'])
b = np.array(['_user', '_123'])

print(np.char.add(a, b))

['hello_user' 'world_123']


In [105]:
# np.char.multiply()

print(np.char.multiply(a, 2))

['hellohello' 'worldworld']


In [106]:
# np.char.upper() / lower() / capitalize()

a = np.array(['hello', 'WORLD'])

print(np.char.upper(a)) 
print(np.char.lower(a)) 
print(np.char.capitalize(a)) 

['HELLO' 'WORLD']
['hello' 'world']
['Hello' 'World']


In [107]:
# np.char.center()

print(np.char.center(a, 11, fillchar='*'))

['***hello***' '***WORLD***']


In [130]:
def password(value):
    # print(value[-4:])
    p = np.array([value[-4:]])
    print(p)
    print(np.char.center(p, 30, fillchar='*'))

In [131]:
password("canwedoitlaterpass")

['pass']
['*************pass*************']


In [132]:
# np.char.replace()
a = np.array(['data_science', 'machine_learning'])

print(np.char.replace(a, '_', ' '))

['data science' 'machine learning']


In [133]:
# np.char.split()

print(np.char.split(a, sep='_'))

[list(['data', 'science']) list(['machine', 'learning'])]


In [ ]:
# np.char.find() / np.char.count()
print(np.char.find(a, 'learn')) 
# ['data_science', 'machine_learning']

[-1  8]


In [135]:
print(np.char.count(a, 'a'))
print(np.char.count(a, 'data'))

[2 2]
[1 0]


# NUMPY COMPLETED

### PANDAS INTRO

In [ ]:
# Power Bi / Tableau -> Dashboard tool / Data Analysis (Application)
# Python + Code version Excel + Data visualzation tools + Streamlit

In [ ]:
# uv add pandas
# !pip install pandas

In [ ]:
# !pip install pandas

In [137]:
import pandas as pd

In [139]:
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"


In [140]:
df = pd.read_csv(titanic_dataset_github_url)

In [142]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.head() # shows first 5 rows from dataframe

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [143]:
df.tail() # shows last 5 rows from dataframe

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [144]:
df.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [145]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...                        
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [146]:
df[['Name', 'Age']]

Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [147]:
df.shape

(891, 12)

In [148]:
dir(df)

['Age',
 'Cabin',
 'Embarked',
 'Fare',
 'Name',
 'Parch',
 'PassengerId',
 'Pclass',
 'Sex',
 'SibSp',
 'Survived',
 'T',
 'Ticket',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',