# Array Reshaping and resizing in numpy

###  1. reshape()

Change Shape Without Changing Data

##### Notes:
The total number of elements must remain the same.

reshape() returns a new view if possible (no copy).

You can use -1 to let NumPy infer one dimension:

### 2. ravel() 

Flatten into 1D (returns a view)

Fast and memory-efficient.

Changes reflect in the original array (if no copy made).

In [1]:
import numpy as np

In [3]:
a = np.array([[1, 2], [3, 4]])

In [4]:
a.shape

(2, 2)

In [5]:
print(a.ravel())

[1 2 3 4]


In [6]:
print(a)

[[1 2]
 [3 4]]


In [7]:
a_ravel = a.ravel()
print(a_ravel)
print(id(a))
print(id(a.ravel()))
print(id(a_ravel))

[1 2 3 4]
2150665186416
2150665188048
2149884750768


In [ ]:
# .__array_interface__['data'][0] 

# Attributes gives you the actual memory address where the raw array data begins

In [8]:
print(f"Data address of 'a': {a.__array_interface__['data'][0]}")

Data address of 'a': 2149868715696


In [9]:
print(f"Data address of a.ravel() directly: {a.ravel().__array_interface__['data'][0]}")


Data address of a.ravel() directly: 2149868715696


In [10]:
print(f"Data address of 'a_raven': {a_ravel.__array_interface__['data'][0]}")


Data address of 'a_raven': 2149868715696


In [12]:
a[0][0] = 11

In [13]:
a

array([[11,  2],
       [ 3,  4]])

In [14]:
print(f"Data address of 'a': {a.__array_interface__['data'][0]}")

Data address of 'a': 2149868715696


In [15]:
print(a_ravel)

[11  2  3  4]


In [ ]:
list.append()

### 3. flatten()

Flatten into 1D (returns a copy)

In [17]:
a

array([[11,  2],
       [ 3,  4]])

In [18]:
b = a.flatten()

In [19]:
print(f"Data address of 'a': {a.__array_interface__['data'][0]}")
print(f"Data address of 'b': {b.__array_interface__['data'][0]}")


Data address of 'a': 2149868715696
Data address of 'b': 2149868715216


In [20]:
b

array([11,  2,  3,  4])

### 4. resize()

Resize Array In-place

Unlike reshape(), it can change total size. Data may be truncated or padded with zeros.

In [21]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
a = a.reshape((3,3))

ValueError: cannot reshape array of size 6 into shape (3,3)

In [26]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
a.resize((3,3), refcheck=False) # In-place : means changing the data without reassignment

In [34]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

### 5. squeeze()

Remove single-dimensional axes

Useful for removing extra dimensions from image or model output shapes like (1, 28, 28, 1)

In [ ]:
a = np.array([[[1], [2], [3]]])
print(a.shape)

(2, 3, 1)


In [42]:
b = np.squeeze(a)

In [43]:
print(b.shape)

(3,)


In [44]:
b

array([1, 2, 3])

| Function        | Purpose                        | In-place | Returns Copy/View  |
| --------------- | ------------------------------ | -------- | ------------------ |
| `reshape()`     | Change shape (same size)       | ❌        | View (if possible) |
| `resize()`      | Resize array (can change size) | ✅        | None               |
| `ravel()`       | Flatten array (1D)             | ❌        | View               |
| `flatten()`     | Flatten array (1D)             | ❌        | Copy               |
| `squeeze()`     | Remove dimensions of size 1    | ❌        | New array          |


# Indexing and Slicing in NumPy — Beginner to Advanced

###  1. Basic Indexing (1D Arrays)

Slicing syntax: array[start:stop:step]

In [46]:
arr = np.array([10, 20, 30, 40, 50])

In [47]:
print(arr[0])

10


In [48]:
print(arr[-1])

50


In [49]:
print(arr[4])

50


In [ ]:
# arr = np.array([10, 20, 30, 40, 50])
# array[start:stop(exclusive):step]

print(arr[1:4])

[20 30 40]


In [51]:
print(arr[1:-1])

[20 30 40]


In [52]:
# arr = np.array([10, 20, 30, 40, 50])
# array[start:stop(exclusive):step]

print(arr[0:3])

[10 20 30]


In [53]:
print(arr[:3])

[10 20 30]


In [54]:
# arr = np.array([10, 20, 30, 40, 50])
# array[start:stop(exclusive):step]
# [10, 30, 50]
arr[0:5:2]


array([10, 30, 50])

In [55]:
arr[::2]

array([10, 30, 50])

In [ ]:
arr[::-1] # reversing

array([50, 40, 30, 20, 10])

In [57]:
list_a = [1,2,3,4,5,6,7]
list_a[::-1]

[7, 6, 5, 4, 3, 2, 1]

### 2. Indexing in 2D Arrays

In [58]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [59]:
mat[0][1]

np.int64(2)

In [60]:
mat[0, 1]

np.int64(2)

In [61]:
mat[:, 2]

array([3, 6, 9])

In [62]:
# [[1, 2, 3],
# [4, 5, 6],
# [7, 8, 9]]

# [[2 3]
#  [5 6]]

mat[0:2, 1:]

array([[2, 3],
       [5, 6]])

In [63]:
# [[9 8 7]
#  [6 5 4]
#  [3 2 1]]

mat[::-1, ::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

### 3. Boolean Indexing

In [72]:
arr = np.array([5, 10, 15, 20, 25])

In [65]:
# i want to get all the elements greater than 15

In [66]:
l = []
for i in arr:
    if i > 15:
        l.append(i)
l = np.array(l)
print(l)

[20 25]


In [68]:
arr > 15

array([False, False, False,  True,  True])

In [73]:
arr[arr > 15]

array([20, 25])

### 4. Fancy Indexing

In [69]:
arr = np.array([100, 200, 300, 400, 500])
indices = [0, 2, 4]
print(arr[indices])   

[100 300 500]


In [ ]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [ ]:
mat[mat>5]

array([6, 7, 8, 9])

#

In [ ]:
      
mat[[0,1],
    [2,2]]
  #  ^ ^
  # | |
# --> 0,2 --> 3
# --> 1,2 --> 6

array([3, 6])

### 5. Modifying with Indexing

In [82]:
arr = np.array([1, 2, 3, 4])
arr[2] = 10
print(arr)

[ 1  2 10  4]


In [83]:
arr[arr > 2] = 100
print(arr)

[  1   2 100 100]


### 6. Indexing with np.where()

In [85]:
arr = np.array([10, 15, 20, 25, 30])

In [86]:
idx = np.where(arr > 20)

In [87]:
print(idx)

(array([3, 4]),)


In [88]:
print(arr[idx])

[25 30]
