In [54]:
import time
import numpy as np

In [55]:
a = range(100000000)
b = range(100000000)
start = time.perf_counter()
total_val = [x+y for x, y in zip(a, b)]
end = time.perf_counter()
total_p = end - start
print(total_p)

8.543079099999886


In [56]:
a = np.array(a)
b = np.array(b)
start = time.perf_counter()
total_val = a + b
end = time.perf_counter()
total_n = end - start
print(total_n)
print(f"Numpy is faster than python {total_p/total_n:.2f} percentage")

1.4632570999992822
Numpy is faster than python 5.84 percentage


In [57]:
np.array([1,2,3,4, '76'], dtype=np.float64)


array([ 1.,  2.,  3.,  4., 76.])

In [58]:
arr = np.array([1,2,3,4, '76'])
type(arr[2])

numpy.str_

In [59]:
np.linspace(1,10, 10, dtype=np.int64)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [61]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [62]:
arr = np.zeros((2,3,2,5), dtype=np.int8)
print(arr, end='\n\n\n')
print('Dimentions: ', arr.ndim)
print('', end='\n\n')
print('Shape: ', arr.shape)

[[[[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]]]


Dimentions:  4


Shape:  (2, 3, 2, 5)


In [63]:
arr = np.ones((2,3,2,5), dtype=np.int8)
print(arr, end='\n\n\n')
print('Dimentions: ', arr.ndim)
print('', end='\n\n')
print('Shape: ', arr.shape)

[[[[1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]]]


 [[[1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]]]]


Dimentions:  4


Shape:  (2, 3, 2, 5)


In [64]:
arr = np.full((2,3,2,5), 13, dtype=np.int8)
print(arr, end='\n\n\n')
print('Dimentions: ', arr.ndim)
print('', end='\n\n')
print('Shape: ', arr.shape)

[[[[13 13 13 13 13]
   [13 13 13 13 13]]

  [[13 13 13 13 13]
   [13 13 13 13 13]]

  [[13 13 13 13 13]
   [13 13 13 13 13]]]


 [[[13 13 13 13 13]
   [13 13 13 13 13]]

  [[13 13 13 13 13]
   [13 13 13 13 13]]

  [[13 13 13 13 13]
   [13 13 13 13 13]]]]


Dimentions:  4


Shape:  (2, 3, 2, 5)


### Identity matrix

In [65]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [66]:
np.eye(5,2, dtype=np.int16)

array([[1, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int16)

In [67]:
np.empty((5,5), dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [68]:
np.empty((5), dtype=np.int8)

array([0, 0, 0, 0, 0], dtype=int8)

In [69]:
np.random.rand(3,3,3)

array([[[0.24834311, 0.40211462, 0.99363852],
        [0.51232578, 0.16361185, 0.64441107],
        [0.54253918, 0.4546159 , 0.2582104 ]],

       [[0.53904368, 0.95012056, 0.46828249],
        [0.99372749, 0.43331198, 0.92659358],
        [0.88942266, 0.57937949, 0.94650012]],

       [[0.70182111, 0.45102344, 0.95863665],
        [0.30012649, 0.03801797, 0.87397309],
        [0.23318256, 0.59569502, 0.66795878]]])

In [70]:
arr = np.random.rand(3,3,3)
print(arr.size)
print(arr.itemsize)
print(arr.nbytes)
print(arr.T)

27
8
216
[[[0.86063227 0.42667558 0.17683384]
  [0.88880179 0.4321278  0.90853722]
  [0.54042712 0.12386207 0.27327445]]

 [[0.12947123 0.36594233 0.40703752]
  [0.68945422 0.94188174 0.28388501]
  [0.29685422 0.31667932 0.7836259 ]]

 [[0.93153144 0.16314616 0.10827884]
  [0.29088097 0.89055442 0.5176284 ]
  [0.95317081 0.50680104 0.90677433]]]
