In [59]:
import time
import numpy as np

In [60]:
a = range(100000000)
b = range(100000000)
start = time.perf_counter()
total_val = [x+y for x, y in zip(a, b)]
end = time.perf_counter()
total_p = end - start
print(total_p)

7.793943900003796


In [61]:
a = np.array(a)
b = np.array(b)
start = time.perf_counter()
total_val = a + b
end = time.perf_counter()
total_n = end - start
print(total_n)
print(f"Numpy is faster than python {total_p/total_n:.2f} percentage")

1.1700023000012152
Numpy is faster than python 6.66 percentage


In [62]:
np.array([1,2,3,4, '76'], dtype=np.float64)


array([ 1.,  2.,  3.,  4., 76.])

In [63]:
arr = np.array([1,2,3,4, '76'])
type(arr[2])

numpy.str_

In [64]:
np.linspace(1,10, 10, dtype=np.int64)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [66]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [67]:
arr = np.zeros((2,3,2,5), dtype=np.int8)
print(arr, end='\n\n\n')
print('Dimentions: ', arr.ndim)
print('', end='\n\n')
print('Shape: ', arr.shape)

[[[[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]]]


Dimentions:  4


Shape:  (2, 3, 2, 5)


In [68]:
arr = np.ones((2,3,2,5), dtype=np.int8)
print(arr, end='\n\n\n')
print('Dimentions: ', arr.ndim)
print('', end='\n\n')
print('Shape: ', arr.shape)

[[[[1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]]]


 [[[1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]]]]


Dimentions:  4


Shape:  (2, 3, 2, 5)


In [69]:
arr = np.full((2,3,2,5), 13, dtype=np.int8)
print(arr, end='\n\n\n')
print('Dimentions: ', arr.ndim)
print('', end='\n\n')
print('Shape: ', arr.shape)

[[[[13 13 13 13 13]
   [13 13 13 13 13]]

  [[13 13 13 13 13]
   [13 13 13 13 13]]

  [[13 13 13 13 13]
   [13 13 13 13 13]]]


 [[[13 13 13 13 13]
   [13 13 13 13 13]]

  [[13 13 13 13 13]
   [13 13 13 13 13]]

  [[13 13 13 13 13]
   [13 13 13 13 13]]]]


Dimentions:  4


Shape:  (2, 3, 2, 5)


### Identity matrix

In [70]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [90]:
np.eye(5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [92]:
np.eye(5)[::-1]

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [71]:
np.eye(5,2, dtype=np.int16)

array([[1, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int16)

In [72]:
np.empty((5,5), dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [73]:
np.empty((5), dtype=np.int8)

array([0, 0, 0, 0, 0], dtype=int8)

In [74]:
np.random.rand(3,3,3)

array([[[0.66096718, 0.27536388, 0.34481383],
        [0.06682738, 0.15441812, 0.82499969],
        [0.38686297, 0.46513639, 0.60930449]],

       [[0.9846239 , 0.85820774, 0.90003672],
        [0.60655979, 0.09175671, 0.72781957],
        [0.60898924, 0.00770353, 0.94195852]],

       [[0.39489261, 0.80131527, 0.83855443],
        [0.06170026, 0.02933263, 0.47540691],
        [0.35821361, 0.90179126, 0.28447502]]])

In [75]:
arr = np.random.rand(3,3,3)
print(arr.size)
print(arr.itemsize)
print(arr.nbytes)
print(arr.T)

27
8
216
[[[7.73916017e-01 3.04966232e-01 3.92608696e-01]
  [9.02042364e-02 3.20022436e-01 4.57900185e-01]
  [3.40500007e-02 9.89069027e-01 3.16529221e-01]]

 [[4.76333862e-01 7.34863746e-02 3.42552744e-01]
  [2.40992131e-01 8.02023488e-01 8.25845203e-01]
  [5.06930813e-01 8.11690981e-01 9.83620580e-01]]

 [[8.39209078e-01 1.91297347e-01 9.97343190e-01]
  [5.19071944e-01 2.38173380e-04 4.45883059e-01]
  [5.87267684e-01 2.14426687e-01 9.02031340e-01]]]


In [76]:
np.random.randint(1, 100, 20, dtype=np.int8)

array([ 1, 17, 50, 84, 66,  1,  3, 66, 78, 85, 72, 67, 89, 22, 87, 74, 74,
       96, 38, 70], dtype=int8)

In [77]:
arr = np.random.randint(1, 100, 20, dtype=np.int8)
reshape = arr.reshape((4,-1))
print(reshape)
arr

[[18  4 59 56 60]
 [24 51 86 45 39]
 [30 90 72 41 14]
 [23 46 62 46 47]]


array([18,  4, 59, 56, 60, 24, 51, 86, 45, 39, 30, 90, 72, 41, 14, 23, 46,
       62, 46, 47], dtype=int8)

In [78]:
arr = np.random.randint(1, 100, 20, dtype=np.int8)
arr.resize((4,5))
arr

array([[ 6, 46, 70, 93, 48],
       [38, 93,  9,  1, 47],
       [56, 97, 23, 28,  5],
       [95, 40, 57, 17, 76]], dtype=int8)

In [79]:
arr.ravel()

array([ 6, 46, 70, 93, 48, 38, 93,  9,  1, 47, 56, 97, 23, 28,  5, 95, 40,
       57, 17, 76], dtype=int8)

In [80]:
arr[arr>60]

array([70, 93, 93, 97, 95, 76], dtype=int8)

In [81]:
arr[arr>60].size

6

In [82]:
arr.T

array([[ 6, 38, 56, 95],
       [46, 93, 97, 40],
       [70,  9, 23, 57],
       [93,  1, 28, 17],
       [48, 47,  5, 76]], dtype=int8)